\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={206 A5 Q4},
            pdfauthor={Barbara Rose Hoover},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{206 A5 Q4}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Barbara Rose Hoover}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{12/4/2018}


\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages --------------------------------------------------------------------------------------------- tidyverse 1.2.1 --
\end{verbatim}

\begin{verbatim}
## √ ggplot2 3.0.0     √ purrr   0.2.5
## √ tibble  1.4.2     √ dplyr   0.7.6
## √ tidyr   0.8.1     √ stringr 1.3.1
## √ readr   1.1.1     √ forcats 0.3.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts ------------------------------------------------------------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(stargazer)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Please cite as:
\end{verbatim}

\begin{verbatim}
##  Hlavac, Marek (2018). stargazer: Well-Formatted Regression and Summary Statistics Tables.
\end{verbatim}

\begin{verbatim}
##  R package version 5.2.2. https://CRAN.R-project.org/package=stargazer
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(MASS)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'MASS'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     select
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{faculty <-}\StringTok{ }\KeywordTok{read_csv}\NormalTok{(}\StringTok{"Faculty.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parsed with column specification:
## cols(
##   `Faculty Rank` = col_character(),
##   `Discipline (A = Theoretical, B = Applied)` = col_character(),
##   `Years Since PhD` = col_integer(),
##   `Years Faculty Service` = col_integer(),
##   Sex = col_character(),
##   `Salary ($)` = col_integer()
## )
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{faculty <-}\StringTok{ }\KeywordTok{rename}\NormalTok{(faculty, }\DataTypeTok{discipline =} \StringTok{`}\DataTypeTok{Discipline (A = Theoretical, B = Applied)}\StringTok{`}\NormalTok{, }\DataTypeTok{rank =} \StringTok{`}\DataTypeTok{Faculty Rank}\StringTok{`}\NormalTok{, }\DataTypeTok{yearsphd =} \StringTok{`}\DataTypeTok{Years Since PhD}\StringTok{`}\NormalTok{, }\DataTypeTok{yearsfac =} \StringTok{`}\DataTypeTok{Years Faculty Service}\StringTok{`}\NormalTok{, }\DataTypeTok{sex =}\NormalTok{ Sex, }\DataTypeTok{salary =} \StringTok{`}\DataTypeTok{Salary ($)}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Linear Model

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{salary_lm <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(salary }\OperatorTok{~}\StringTok{ }\NormalTok{rank }\OperatorTok{+}\StringTok{ }\NormalTok{discipline }\OperatorTok{+}\StringTok{ }\NormalTok{yearsphd }\OperatorTok{+}\StringTok{ }\NormalTok{yearsfac }\OperatorTok{+}\StringTok{ }\NormalTok{sex, }\DataTypeTok{data =}\NormalTok{ faculty)}
\KeywordTok{summary}\NormalTok{(salary_lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = salary ~ rank + discipline + yearsphd + yearsfac + 
##     sex, data = faculty)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -65248 -13211  -1775  10384  99592 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   78862.8     4990.3  15.803  < 2e-16 ***
## rankAsstProf -12907.6     4145.3  -3.114  0.00198 ** 
## rankProf      32158.4     3540.6   9.083  < 2e-16 ***
## disciplineB   14417.6     2342.9   6.154 1.88e-09 ***
## yearsphd        535.1      241.0   2.220  0.02698 *  
## yearsfac       -489.5      211.9  -2.310  0.02143 *  
## sexMale        4783.5     3858.7   1.240  0.21584    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 22540 on 390 degrees of freedom
## Multiple R-squared:  0.4547, Adjusted R-squared:  0.4463 
## F-statistic:  54.2 on 6 and 390 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#p-value for sex 0.21584}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{salary5_lm<-}\KeywordTok{lm}\NormalTok{(salary }\OperatorTok{~}\StringTok{ }\NormalTok{rank }\OperatorTok{+}\StringTok{ }\NormalTok{discipline, }\DataTypeTok{data =}\NormalTok{ faculty)}
\KeywordTok{summary}\NormalTok{(salary5_lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = salary ~ rank + discipline, data = faculty)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -65990 -14049  -1288  10760  97996 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     85706       3142  27.273  < 2e-16 ***
## rankAsstProf   -13762       3961  -3.475 0.000569 ***
## rankProf        34082       3160  10.786  < 2e-16 ***
## disciplineB     13761       2296   5.993 4.65e-09 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 22650 on 393 degrees of freedom
## Multiple R-squared:  0.445,  Adjusted R-squared:  0.4407 
## F-statistic:   105 on 3 and 393 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{AIC}\NormalTok{(salary5_lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9094.823
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{salary2_lm<-}\KeywordTok{lm}\NormalTok{(salary }\OperatorTok{~}\StringTok{ }\NormalTok{rank }\OperatorTok{+}\StringTok{ }\NormalTok{discipline }\OperatorTok{+}\StringTok{ }\NormalTok{sex, }\DataTypeTok{data =}\NormalTok{ faculty)}
\KeywordTok{summary}\NormalTok{(salary2_lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = salary ~ rank + discipline + sex, data = faculty)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -66268 -14127  -1566  10813  97718 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     81947       4506  18.187  < 2e-16 ***
## rankAsstProf   -13723       3959  -3.466 0.000586 ***
## rankProf        33680       3177  10.600  < 2e-16 ***
## disciplineB     13709       2295   5.972 5.25e-09 ***
## sexMale          4492       3860   1.164 0.245291    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 22640 on 392 degrees of freedom
## Multiple R-squared:  0.4469, Adjusted R-squared:  0.4412 
## F-statistic: 79.18 on 4 and 392 DF,  p-value: < 2.2e-16
\end{verbatim}

\paragraph{This explains 44\% (0.4407) of the variation seen in
salary.}\label{this-explains-44-0.4407-of-the-variation-seen-in-salary.}

\subsubsection{Years since receiving PhD and Years on faculty were found
to be colinear, with a correlation coefficient of
0.9096491.}\label{years-since-receiving-phd-and-years-on-faculty-were-found-to-be-colinear-with-a-correlation-coefficient-of-0.9096491.}

\subsubsection{Yearsfac has a negative coefficient, indicating that as
years spent as faculty increases, salary decreases. This is not logical,
and was omitted from the final
lm.}\label{yearsfac-has-a-negative-coefficient-indicating-that-as-years-spent-as-faculty-increases-salary-decreases.-this-is-not-logical-and-was-omitted-from-the-final-lm.}

\subsubsection{Rank appeared to be closely tied to Yearsphd and
Yearsfac. When lm were run ony including rank, yearsphd, yearsfac, the
adjusted R\^{}2 were 0.4469, 0.2447, 0.1646
respectively.}\label{rank-appeared-to-be-closely-tied-to-yearsphd-and-yearsfac.-when-lm-were-run-ony-including-rank-yearsphd-yearsfac-the-adjusted-r2-were-0.4469-0.2447-0.1646-respectively.}

\subsubsection{lm was run for a version including both rank and
yearsphd, and one for only including rank. Resulting adjusted R\^{}2 was
0.4401, 0.4412 and the AIC was 9097.22, 9095.454 respectively. Seeing as
adjusted R\^{}2 was not improved with the additional variable, yearsphd
was dropped from the final
model.}\label{lm-was-run-for-a-version-including-both-rank-and-yearsphd-and-one-for-only-including-rank.-resulting-adjusted-r2-was-0.4401-0.4412-and-the-aic-was-9097.22-9095.454-respectively.-seeing-as-adjusted-r2-was-not-improved-with-the-additional-variable-yearsphd-was-dropped-from-the-final-model.}

\subsubsection{Although the p-value for gender was not significant in
the final model (p=0.245291), gender was included because gender
accounts for a \$4492 difference in salary. This fact is significant
because this means that with all other variables constant, females will
be paid \$4492 less then
men.}\label{although-the-p-value-for-gender-was-not-significant-in-the-final-model-p0.245291-gender-was-included-because-gender-accounts-for-a-4492-difference-in-salary.-this-fact-is-significant-because-this-means-that-with-all-other-variables-constant-females-will-be-paid-4492-less-then-men.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{salary3_lm<-}\KeywordTok{lm}\NormalTok{(salary }\OperatorTok{~}\StringTok{ }\NormalTok{rank }\OperatorTok{+}\StringTok{ }\NormalTok{discipline }\OperatorTok{+}\StringTok{ }\NormalTok{yearsphd }\OperatorTok{+}\StringTok{ }\NormalTok{sex, }\DataTypeTok{data =}\NormalTok{ faculty)}
\KeywordTok{summary}\NormalTok{(salary3_lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = salary ~ rank + discipline + yearsphd + sex, data = faculty)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -67451 -13860  -1549  10716  97023 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   80988.47    4931.84  16.422  < 2e-16 ***
## rankAsstProf -13104.15    4167.31  -3.145  0.00179 ** 
## rankProf      32928.40    3544.40   9.290  < 2e-16 ***
## disciplineB   13937.47    2346.53   5.940 6.32e-09 ***
## yearsphd         61.01     127.01   0.480  0.63124    
## sexMale        4349.37    3875.39   1.122  0.26242    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 22660 on 391 degrees of freedom
## Multiple R-squared:  0.4472, Adjusted R-squared:  0.4401 
## F-statistic: 63.27 on 5 and 391 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{salary4_lm<-}\KeywordTok{lm}\NormalTok{(salary }\OperatorTok{~}\StringTok{ }\NormalTok{rank }\OperatorTok{+}\StringTok{ }\NormalTok{discipline }\OperatorTok{+}\StringTok{ }\NormalTok{yearsfac }\OperatorTok{+}\StringTok{ }\NormalTok{sex, }\DataTypeTok{data =}\NormalTok{ faculty)}
\KeywordTok{summary}\NormalTok{(salary4_lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = salary ~ rank + discipline + yearsfac + sex, data = faculty)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -64202 -14255  -1533  10571  99163 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   82912.07    4668.39  17.760  < 2e-16 ***
## rankAsstProf -14560.40    4098.32  -3.553 0.000428 ***
## rankProf      34599.24    3382.52  10.229  < 2e-16 ***
## disciplineB   13473.38    2315.50   5.819 1.24e-08 ***
## yearsfac        -88.78     111.64  -0.795 0.426958    
## sexMale        4771.25    3878.00   1.230 0.219311    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 22650 on 391 degrees of freedom
## Multiple R-squared:  0.4478, Adjusted R-squared:  0.4407 
## F-statistic: 63.41 on 5 and 391 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#negative coefficient for yearsfac. Does not make sense }
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{AIC}\NormalTok{(salary_lm) }\CommentTok{#9093.826, 0.4547, 0.4463}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9093.826
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{AIC}\NormalTok{(salary2_lm) }\CommentTok{#9095.454, 0.4469, 0.4412 <-choose this one }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9095.454
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{AIC}\NormalTok{(salary3_lm) }\CommentTok{#9097.22, 0.4472, 0.4401}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9097.22
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{AIC}\NormalTok{(salary4_lm) }\CommentTok{#9096.813, 0.4478, 0.4407 }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9096.813
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{AIC}\NormalTok{(salary5_lm) }\CommentTok{#9094.823, 0.445, 0.4407 <- Possibly compare. Model excludes gender}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9094.823
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{stargazer}\NormalTok{(salary2_lm, }\DataTypeTok{type=}\StringTok{"html"}\NormalTok{,}
          \DataTypeTok{title =} \StringTok{"Iris regression results."}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Iris regression results.

Dependent variable:

salary

rankAsstProf

-13,723.420***

(3,959.014)

rankProf

33,679.900***

(3,177.338)

disciplineB

13,708.690***

(2,295.437)

sexMale

4,491.801

(3,860.240)

Constant

81,946.950***

(4,505.769)

Observations

397

R2

0.447

Adjusted R2

0.441

Residual Std. Error

22,640.990 (df = 392)

F Statistic

79.180*** (df = 4; 392)

Note:

\emph{p\textless{}0.1; \textbf{p\textless{}0.05; }}p\textless{}0.01

\subsubsection{Exploring rank, yearsfac,
yearsphd}\label{exploring-rank-yearsfac-yearsphd}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rank_lm<-}\KeywordTok{lm}\NormalTok{(salary }\OperatorTok{~}\StringTok{ }\NormalTok{rank }\OperatorTok{+}\StringTok{ }\NormalTok{discipline  }\OperatorTok{+}\StringTok{ }\NormalTok{sex, }\DataTypeTok{data =}\NormalTok{ faculty)}
\KeywordTok{summary}\NormalTok{(rank_lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = salary ~ rank + discipline + sex, data = faculty)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -66268 -14127  -1566  10813  97718 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     81947       4506  18.187  < 2e-16 ***
## rankAsstProf   -13723       3959  -3.466 0.000586 ***
## rankProf        33680       3177  10.600  < 2e-16 ***
## disciplineB     13709       2295   5.972 5.25e-09 ***
## sexMale          4492       3860   1.164 0.245291    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 22640 on 392 degrees of freedom
## Multiple R-squared:  0.4469, Adjusted R-squared:  0.4412 
## F-statistic: 79.18 on 4 and 392 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rank_lm2<-}\KeywordTok{lm}\NormalTok{(salary }\OperatorTok{~}\StringTok{ }\NormalTok{yearsfac }\OperatorTok{+}\StringTok{ }\NormalTok{discipline  }\OperatorTok{+}\StringTok{ }\NormalTok{sex, }\DataTypeTok{data =}\NormalTok{ faculty)}
\KeywordTok{summary}\NormalTok{(rank_lm2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = salary ~ yearsfac + discipline + sex, data = faculty)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -77424 -19404  -4635  15539 105391 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  84361.1     4941.4  17.072  < 2e-16 ***
## yearsfac       832.2      110.2   7.550 3.07e-13 ***
## disciplineB  13033.8     2840.3   4.589 6.01e-06 ***
## sexMale       8423.3     4744.5   1.775   0.0766 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 27790 on 393 degrees of freedom
## Multiple R-squared:  0.1646, Adjusted R-squared:  0.1582 
## F-statistic: 25.81 on 3 and 393 DF,  p-value: 2.928e-15
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rank_lm3<-}\KeywordTok{lm}\NormalTok{(salary }\OperatorTok{~}\StringTok{ }\NormalTok{yearsphd }\OperatorTok{+}\StringTok{ }\NormalTok{discipline  }\OperatorTok{+}\StringTok{ }\NormalTok{sex, }\DataTypeTok{data =}\NormalTok{ faculty)}
\KeywordTok{summary}\NormalTok{(rank_lm3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = salary ~ yearsphd + discipline + sex, data = faculty)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -79850 -17491  -3639  15485  92883 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  74535.1     4932.1  15.112  < 2e-16 ***
## yearsphd      1093.3      106.8  10.232  < 2e-16 ***
## disciplineB  15626.3     2730.4   5.723 2.08e-08 ***
## sexMale       6956.3     4509.2   1.543    0.124    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 26420 on 393 degrees of freedom
## Multiple R-squared:  0.2447, Adjusted R-squared:  0.2389 
## F-statistic: 42.43 on 3 and 393 DF,  p-value: < 2.2e-16
\end{verbatim}

\section{Data Exploration}\label{data-exploration}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plt<-}\KeywordTok{ggplot}\NormalTok{(faculty, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y=}\NormalTok{salary, }\DataTypeTok{x=}\NormalTok{yearsphd, }\DataTypeTok{group=}\NormalTok{sex))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se =} \OtherTok{FALSE}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{color=}\NormalTok{sex))}
\NormalTok{plt}
\end{Highlighting}
\end{Shaded}

\includegraphics{206_A5_Q4_files/figure-latex/salary in yearsphd comparing gender-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plt2<-}\KeywordTok{ggplot}\NormalTok{(faculty, }\DataTypeTok{group=}\NormalTok{discipline)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{discipline, }\DataTypeTok{y=}\NormalTok{salary, }\DataTypeTok{color=}\NormalTok{rank, }\DataTypeTok{shape=}\NormalTok{sex), }\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(}\DataTypeTok{width =}\NormalTok{ .}\DecValTok{5}\NormalTok{))}
\NormalTok{plt2}
\end{Highlighting}
\end{Shaded}

\includegraphics{206_A5_Q4_files/figure-latex/salary by rank and gender-1.pdf}

\section{Exploring dependence}\label{exploring-dependence}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Rank is not independent of gender. This is something to consider. }
\NormalTok{t.rank<-}\KeywordTok{table}\NormalTok{(faculty}\OperatorTok{$}\NormalTok{sex, faculty}\OperatorTok{$}\NormalTok{rank)}
\NormalTok{ct<-}\KeywordTok{chisq.test}\NormalTok{(t.rank)}
\NormalTok{ct}\OperatorTok{$}\NormalTok{expected}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         
##          AssocProf  AsstProf      Prof
##   Female  6.287154  6.581864  26.13098
##   Male   57.712846 60.418136 239.86902
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ct}\OperatorTok{$}\NormalTok{observed}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         
##          AssocProf AsstProf Prof
##   Female        10       11   18
##   Male          54       56  248
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ct}\OperatorTok{$}\NormalTok{stdres}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         
##          AssocProf  AsstProf      Prof
##   Female  1.702577  1.989100 -2.915939
##   Male   -1.702577 -1.989100  2.915939
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ct ##p-value = 0.01408}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test
## 
## data:  t.rank
## X-squared = 8.5259, df = 2, p-value = 0.01408
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{##years fac vs. years phd}
\KeywordTok{cor}\NormalTok{(faculty}\OperatorTok{$}\NormalTok{yearsphd, faculty}\OperatorTok{$}\NormalTok{yearsfac) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9096491
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#0.9096491}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plt4<-}\KeywordTok{ggplot}\NormalTok{(faculty, }\DataTypeTok{group=}\NormalTok{rank)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{yearsphd, }\DataTypeTok{y=}\NormalTok{salary, }\DataTypeTok{color=}\NormalTok{rank), }\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(}\DataTypeTok{width =}\NormalTok{ .}\DecValTok{5}\NormalTok{))}
\NormalTok{plt4}
\end{Highlighting}
\end{Shaded}

\includegraphics{206_A5_Q4_files/figure-latex/salary by rank and yearsphd-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plt5<-}\KeywordTok{ggplot}\NormalTok{(faculty, }\DataTypeTok{group=}\NormalTok{rank)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{yearsfac, }\DataTypeTok{y=}\NormalTok{salary, }\DataTypeTok{color=}\NormalTok{rank), }\DataTypeTok{position=}\KeywordTok{position_dodge}\NormalTok{(}\DataTypeTok{width =}\NormalTok{ .}\DecValTok{5}\NormalTok{))}
\NormalTok{plt5}
\end{Highlighting}
\end{Shaded}

\includegraphics{206_A5_Q4_files/figure-latex/salary by rank and yearsfac-1.pdf}


\end{document}
