---
title: "206 Assignment 5"
author: "Barbara Rose Hoover"
date: "11/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
library(tidyverse)
library(stargazer)
library(knitr)
library(kableExtra)
library(extrafont)
```
```{r message=FALSE}
faculty <- read_csv("Faculty.csv")
mf_grad <- read_csv("mfgrad.csv")
med_salary<-read_csv("salary.csv")
phd_field<-read_csv("phd_field.csv")

```

##Making Subset 
```{r}
mf_grad_sub<-select(mf_grad, Year:`Total Female`)
```


```{r}
enroll_graph <- ggplot(mf_grad_sub) +
  geom_line(aes(color="Male", x=Year, y=`Total Male`)) +
  geom_line(aes(color="Female", x=Year, y = `Total Female`))

enroll_graph
```


```{r correlation coefficient}
# Closer to 1, the better 
#Same as pearson's test
cor(mf_grad_sub$`Total Male`, mf_grad_sub$Year)
cor(mf_grad_sub$`Total Female`, mf_grad_sub$Year)

#Numbers suggest linear releation between year and # of students (both genders) 
```

```{r linear model for male}
m_grad_lm<-lm(formula = `Total Male` ~ Year, data = mf_grad_sub)
summary(m_grad_lm)

```

```{r pearson, echo = FALSE}

m_grad_pc<-cor.test(mf_grad_sub$Year, mf_grad_sub$`Total Male`)

```

```{r graph, fig.height = 4, fig.width = 6, echo = FALSE}

predicted <- predict(m_grad_lm, interval = "confidence", level = 0.95)
full_data <- data.frame(mf_grad_sub, predicted)

ggplot(full_data, aes(x = Year, y = Total.Male)) + 
  geom_point(color="dodgerblue3") +
  geom_line(aes(x = Year, y = fit)) +
  geom_ribbon(aes(x = Year, ymin = lwr, ymax = upr), alpha = 0.3) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"), 
        text = element_text(family = "Times New Roman")) +
  xlab("Year") +
  ylab("Number of Male Graduates Enrolled") +
  annotate("text", 
           x = 1980, 
           y = 1500000, 
           label = "y = 9069x -17112153", 
           family = "Times New Roman", 
           size = 5) +
  annotate("text", 
           x = 1980, 
           y = 1300000, 
           label = "italic(R)^2 == 0.85", 
           parse = TRUE, 
           family = "Times New Roman", 
           size = 5)+
  scale_y_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE), limits = c(260000,1720000))
```
\newline

**Figure 1. Trends in male (left graph) and female (right graph) graduate enrollmet in the United States from 1967-2015. Actual numbers are indicated as dots. Solid line represents the linear model fit for each respective gender, with the shaded region representing the 95% confidence interval. 


```{r linear model for female}
f_grad_lm<-lm(formula = `Total Female` ~ Year, data = mf_grad_sub)
summary(f_grad_lm)

```

```{r, female pearsons R, echo = FALSE}

f_grad_pc<-cor.test(mf_grad_sub$Year, mf_grad_sub$`Total Female`)
f_grad_pc

```

```{r female graph, fig.height = 4, fig.width = 6, echo = FALSE}

f_predicted <- predict(f_grad_lm, interval = "confidence", level = 0.95)
f_full_data <- data.frame(mf_grad_sub, f_predicted)

ggplot(f_full_data, aes(x = Year, y = Total.Female)) + 
  geom_point(color="red") +
  geom_line(aes(x = Year, y = fit)) +
  geom_ribbon(aes(x = Year, ymin = lwr, ymax = upr), alpha = 0.3) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"), 
        text = element_text(family = "Times New Roman")) +
  xlab("Year") +
  ylab("Number of Female Graduates Enrolled") +
  annotate("text", 
           x = 1980, 
           y = 1500000, 
           label = "y = 30130x -58960000", 
           family = "Times New Roman", 
           size = 5) +
  annotate("text", 
           x = 1980, 
           y = 1300000, 
           label = "italic(R)^2 == 0.98", 
           parse = TRUE, 
           family = "Times New Roman", 
           size = 5)+
  scale_y_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE), limits = c(260000,1720000))+
  labs(caption = "Source: U.S. Department of Education")
```
