---
title: "Q2_ Assignment 5_206"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r library}
library(tidyverse)
library(stargazer)
library(knitr)
library(kableExtra)
library(extrafont)
```

```{r message=FALSE}
faculty <- read_csv("Faculty.csv")
mf_grad <- read_csv("mfgrad.csv")
med_salary<-read_csv("salary.csv")
phd_field<-read_csv("phd_field.csv")
phd_g<-read_csv("PhDs .csv") ##contains percent women (out of men and women) in the field 
```

```{r}
View(phd_field)
row.names(phd_field) <- phd_field$Category

```


```{r data for f}
f_phd_field<-select(phd_field, starts_with("f"))
f_phd_field<-f_phd_field[2:5,]
```

```{r}
f_phd_chi <- chisq.test(f_phd_field)
f_phd_chi


f_phd_chi$observed
round(f_phd_chi$expected,0)
f_phd_chi$stdres
```



```{r}
f_graph<-ggplot(phd_g, aes(Year, Percent, group=`Field of Study`, color =`Field of Study` )) +
  geom_line()+
  scale_x_continuous(breaks=seq(1985,2015,5), limits=c(1984, 2016))+
  scale_y_continuous(limits=c(0, 100), breaks=seq(0,100,10))+
  labs(title = "Doctorate awarded to women, by broad field of study: 1985-2015", x = "Year", y = "Percent (%)")+
  theme(legend.position = c(0.2, 0.8),       
      panel.grid.major.x = element_blank(),
      ##panel.grid.major.y = element_line(colour = "grey"),
      panel.grid.minor = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      axis.line.x= element_blank(), 
      panel.background = element_rect(fill = "white"),
      legend.box.background = element_rect(colour = "grey"))

f_graph

```
```{r}
ggplot(f_phd_field, aes(x=Category, y=len, fill=supp)) +
geom_bar(stat="identity", position=position_dodge())
```

```{r}
matrix<-as.matrix(f_phd_field)
f_phd_prop<-prop.table(matrix, 2)

female_phd_graph <- ggplot(matrix, aes(x = Year)) +
  geom_col(aes(y = Number, fill = Field), position = "dodge") +
  scale_x_continuous(breaks = seq(1985, 2015, by = 15), expand = c(0, 0)) +
  scale_y_continuous(lim = c(0, 5000), expand = c(0,0)) +
  xlab("Year") +
  ylab("Number of Students") +
  ggtitle("Female PhD Recipients by Field") +
  theme_classic()
```


